In [1]:
import numpy as n


In [4]:
runs=n.zeros([3,4],dtype='int16')

In [5]:
runs


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [6]:
Ballbyball=n.ones([2,3,4],dtype='int16')

In [7]:
Ballbyball

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
OverNumbers=n.arange(10,25,5)

In [12]:
OverNumbers


array([10, 15, 20])

In [13]:
RequiredRunRatePoints=n.linspace(0,2,9
                                )

In [14]:
RequiredRunRatePoints


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
FixedTargetGrid=n.full([2,2],7)

In [16]:
FixedTargetGrid


array([[7, 7],
       [7, 7]])

In [20]:
perfectconsistency=n.eye(2,2,dtype='int16')

In [21]:
perfectconsistency


array([[1, 0],
       [0, 1]], dtype=int16)

In [25]:
uncertainform=n.random.random([2,2]);

In [26]:
uncertainform


array([[0.44259601, 0.49551754],
       [0.33485864, 0.85098314]])

In [28]:
uncertainform.shape

(2, 2)

In [29]:
len(uncertainform
   )

2

In [31]:
a=n.array([2,3,4,5])

In [32]:
b=n.array([1,2,3,4])

In [35]:
n.subtract(a,b)

array([1, 1, 1, 1])

In [36]:
a,b

(array([2, 3, 4, 5]), array([1, 2, 3, 4]))

In [38]:
c=n.add(a,b)

In [39]:
c


array([3, 5, 7, 9])

In [40]:
a/b

array([2.        , 1.5       , 1.33333333, 1.25      ])

In [41]:
a*b


array([ 2,  6, 12, 20])

In [43]:
n.sqrt(a)

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [44]:
a.sum()


np.int64(14)